### ISSUE TITLE
Omit final semicolon in block

### ISSUE THREAD

**Issue by yet-another-account** [aaronryank/shortC#1]
Auto insert semicolons right before closing curly brackets, because those are obvious.

**Comment by aaronryank** [comment]
Semicolons are not always used right before closing curly braces. `char str[100] = {0};`

**Comment by aaronryank** [comment]
Partial fix: Auto-inserts semicolon before final closing curly brace.

**Comment by aaronryank** [comment]
I think this is as good as it's going to get. It now auto-inserts a lot of closing things. Thanks for the great suggestion.
