### ISSUE TITLE
Add BKNVYZ and characters that aren't used in C

### ISSUE THREAD

**Issue by aaronryank** [aaronryank/shortC#4]
Translate characters that aren't used in C, e.g. \` @ $

**Comment by CatsAreFluffy** [comment]
`argc` and `argv`

**Comment by aaronryank** [comment]
`BZ$@` and the backtick are now substituted. See README.

**Comment by aaronryank** [comment]
@CatsAreFluffy  `argv` has been implemented. If three characters are still open in two weeks, I'll add `argc`. As of now, I don't see it used much, and it will only save two or three bytes, depending on the situation.

**Comment by aaronryank** [comment]
Pretty sure this is done especially seeing as how I don't work on this language anymore
